StoDevX/stograde

cs251tk/common/__init__.py, cs251tk/common/pluck.py, cs251tk/toolkit/tabulate.py
This is the piece of code that fails the most, usually at the start of the semester when no homeworks or labs have been turned in.
This PR removes a function, `pluck`, which is replaced by the `[item['key'] for item in iter]` convention.
This also tweaks the logic about when to print a warning about empty homework lists, so this should avoid the error entirely.
=> Extract the hw number fetching from the tabulate() function

.travis.yml
Now, when a new tag is pushed and built by Travis, it will go ahead and publish that as a release on PyPI.
I don't think you can make new tags from Github yet, though (releases don't count), so we can't quite release entirely from the website yet.
However, this _will_ allow @rye (or anyone with commit access) to deploy new releases O_o
=> Add TravisCI /  PyPI release integration

cs251tk/common/test_chdir.py, cs251tk/common/test_dirsize.py, cs251tk/toolkit/test_tabulate.py
Goin' up!
Next up, the single buggiest piece of code: `tabulate.py`'s `get_nums` function.
After that, `tabulate` itself.
=> Add tests for common/chdir, common/dirsize, and about half of the funcs in tabulate

cs251tk/common/find_unmerged_branches_in_cwd.py, cs251tk/common/run.py, cs251tk/student/checkout.py, cs251tk/student/markdownify.py, setup.py
Two main things:
1. I removed the support for calling run() with multiple args as the command to run: `run('git', 'log')` instead of `run(['git', 'log'])`. Nothing used that syntax anymore.
2. I renamed the `input` argument to `input_data`
It's got a much cleaner function signature now.
=> Clean up run()

.travis.yml, cs251tk/common/test_find_unmerged_branches_in_cwd.py
find_unmerged_branches is used to record branches in the repo that haven't been merged into master, for some of the later assignments.
It records into the log file, eventually.
=> Add find_unmerged_branches tests

tox.ini
We had to use the git repo directly for a bit, because the pytest plugin wasn't released yet.
Now it is!
=> use pypi pyfakefs package

cs251tk/toolkit/tabulate.py, cs251tk/toolkit/test_tabulate.py, tox.ini
This PR also solves once-and-for-all the problem of `max() cannot find the max of an empty sequence` – it turns out that `max()` takes an optional named argument `default=`, which it can use when given an empty sequence. So. I wish I'd discovered that a long time ago…
=> Finish off tests for tabulate.py

script/run-docker
A simple solution: rather than aborting if we don't have the Docker image yet pulled, try and pull it.
=> Install Docker Image If Not Yet Pulled

cs251tk/cli/cs251tk.py, cs251tk/toolkit/args.py, cs251tk/toolkit/find_update.py
Sometimes, you just don't want it to look for an update.
@rye, you might want this for Docker?
This PR also adds an update check timeout.
=> Add --skip-update-check flag

cs251tk/cli/cs251tk.py, cs251tk/toolkit/args.py, cs251tk/toolkit/process_student.py, cs251tk/toolkit/tabulate.py, cs251tk/toolkit/test_args.py
The primary goal of this PR was to remove all uses of the `args[string]` pattern, where we treat `args` as this giant black boxed blob that we just pass around to any function that needs an argument.
Instead, this uses Python's keyword arguments features to allow the functions to require arguments.
```python
def function(*, a, b):
pass
```
This PR also splits `massage_args` into three functions: `get_students`, `get_assignments`, and `compute_stogit_url`, each of which now has a single responsibility, instead of the previous
situation where `massage_args` had all three jobs.
=> No more args[]

cs251tk/specs/load.py
This PR adds checks for spec dependencies, as discussed in https://github.com/StoDevX/cs251-toolkit/issues/37: 
The current implementation simply prints a warning at program startup if the files cannot be found. We will need to add the "binary.h" file as a dependency of hw3 before this warning will be printed, though.
=> Add checks for spec dependencies

cs251tk/common/find_unmerged_branches_in_cwd.py, cs251tk/common/run.py, cs251tk/common/test_run.py, cs251tk/student/checkout.py, cs251tk/student/clone.py, cs251tk/student/markdownify/markdownify.py, cs251tk/student/markdownify/pipe.py, cs251tk/student/markdownify/process_file.py, cs251tk/student/record.py, cs251tk/student/stash.py, cs251tk/toolkit/__main__.py, cs251tk/toolkit/args.py, cs251tk/toolkit/process_student.py
TL;DR: `cs251tk --interact`.
---
Some submissions require interaction with the program to properly evaluate them, such as the story assignments from homeworks 4 and 5.
This PR adds the `--interact` flag, which runs one submission at a time, dropping you into a psuedo-tty (I think) where you can interact with the submitted program.
When the program is done, you can send EOF (<kbd>^D</kbd>, control-D) to exit the interaction.
After each interaction, you can easily run the submission again by answering the question "Do you want to run the submission again? [y/N]", which defaults to "no". (Examples of when you might want to run it again: `countup.cpp`, `countdown.cpp`.)
This mode offers no infinite loop protection, but <kbd>^C</kbd> should exit the submitted program while keeping the toolkit …
=> Allow interacting with submissions

cs251tk/specs/__init__.py, cs251tk/specs/load.py, cs251tk/specs/util.py, cs251tk/toolkit/__main__.py
So, ah, I realized that the spec dependency check … wasn't actually checking anything.
So this fixes that.
This also moves the check into main(), so we can only check the specs we're actually going to use.
Closes #52.
=> Spec dependent file check fixes

cs251tk/student/markdownify/process_file.py
*Closes #68*.
This PR adds `timeout=30` to the compilation command run.  I don't think there's a need to configure this variable.  This is the same as how we do running, so yeah.
=> Timeout on compilation after 30 seconds

script/run-docker
This will let us use the full width of the terminal rather than just assuming an 80-col limit.
I think I had removed these previously, but whatever.
=> Use the -t flag to allocate a Pseudo-TTY when running

.travis.yml
TravisCI is moving away from these images; IIRC, sometime in November `sudo: false` will just have no effect anymore.
=> Allow travis to reroute our builds

cs251tk/toolkit/__main__.py, cs251tk/toolkit/find_update.py, setup.py
- Added a `strip()` before lines are checked to see if they begin with `'<a'` - this was the main issue
- Increased timeout to 0.5s (from 0.01s) - 0.5 was the lowest reliable time I found. Maybe could be higher for slower connections.
- Reordered arguments in `main` (it said your current version was available and that you have the new version)
- Change `--update` to `--upgrade` in output
- Changed "update available" message to print to stderr
=> Fix update check

Dockerfile
This drops the Docker image size from 946MB to 395MB.
=> Change base image to python3-slim and install required packages

cs251tk/common/__init__.py, cs251tk/common/check_submit_date.py, cs251tk/student/markdownify/check_submit_date.py, cs251tk/student/markdownify/markdownify.py
Fixes #92.
Fixes two problems:
- If the student doesn't commit any files listed in the spec but still created the directory, returns ERROR as the date instead of throwing an exception at `return min(dates).strftime("%x %X")`.
- If the student committed a file with the wrong capitalization (which causes `git log` to print nothing), don't allow `dates.append(parse(res.splitlines()[0]))` to run which would cause an exception.
Moved `check_submit_date.py` to common.
=> Fix date check

cs251tk/toolkit/__main__.py
A HD TA contacted me this weekend asking why the toolkit wasn't setting up the student directories properly. The reason was because he forgot to include the `--course hd` flag. This prevents that from happening by changing the stogit url if the specs are being downloaded for the first time.
Also removed logging import (not used anymore).
=> Improve first run experience for users

Dockerfile
Since moving to a slim-based base image, this is no longer necessary.
In fact, this produces a 0B layer, as it does not change any files.
From `dive stodevx/cs251-toolkit:latest`:
(Notice how Dive reports no removed files on the right when inspecting just the changes in the `apt-get clean` layer.)
Also, slim is configured to never allow those files to persist.
=> Dockerfile: Remove unnecessary call to apt-get clean

cs251tk/student/analyze.py, cs251tk/student/markdownify/markdownify.py, cs251tk/student/record.py, cs251tk/toolkit/__main__.py, cs251tk/toolkit/args.py, cs251tk/toolkit/process_student.py
- Removes the need to copy files to a `students/username` directory before running toolkit in gitlab-ci
With --ci:
- Determines the student and course automatically using the CI_PROJECT_NAME and CI_PROJECT_NAMESPACE environment variables
- Skips unnecessary operations that aren't relevant to ci
New .gitlab-ci.yml:
```
image: 'stodevx/cs251-toolkit:v2.#.#'
build:
stage: build
script:
- cs251tk --ci
```
=> Improve ci flag

cs251tk/student/markdownify/process_file.py, cs251tk/toolkit/__main__.py
- Fix an issue where all files were treated like web files (pausing after each file) if `--web` was used, regardless of if the file in the spec had `web: true`
- Create the server directory if it doesn't exist, preventing file not found errors when compiling web files
- Use keyword arguments for compile_file
=> Improve web flag

Dockerfile, cs251tk/student/markdownify/markdownify.py, cs251tk/student/markdownify/process_file.py, cs251tk/student/record.py, cs251tk/toolkit/__main__.py, cs251tk/toolkit/args.py, cs251tk/toolkit/process_student.py, cs251tk/webapp/server.py, cs251tk/webapp/web_cli.py, setup.py
Adds a new cli using PyInquirer that is used if the `--web` flag is included.
- Git repos are pulled first, then the cli is started.
- The user chooses a student from the first menu.
- Another menu will appear with a list of the web files in the spec (files marked with `web: true`). If a student is missing a file,  `MISSING` is appended to the end of the file name.
- Choosing one of the files will compile the file so it is run by the server.
- The user can choose as many files as they want before selecting the `BACK` option, returning them to the first menu.
- The user can then:
- choose another student
- select `QUIT` to quit the application, or
- select `LOG and QUIT` to create and print the table before quitting
- `NO SUBMISSION` will be appended to a student's id after it was selected …
=> Add new interactive cli for grading web files

cs251tk/toolkit/__main__.py
Add support for a .cs251tkignore file to be added to the student's home directory that specifies which assignments should not be checked.
This is only applicable when the --ci flag is used.
=> Add support for .cs251tkignore files

cs251tk/specs/util.py
Missing optional files were causing assignments to be marked as partially complete even if all required files were present. This removes optional files from the analysis.
=> Optional files don't cause assignment to be marked as partial

cs251tk/toolkit/__main__.py
Found that when the toolkit is run in gitlab ci, if there was no .cs251tkignore file, it would crash.
This should be v2.7.1
=> Fix issue with toolkit crashing when .cs251tkignore not present

stograde/specs/__init__.py, stograde/specs/util.py, stograde/student/markdownify/add_remove_supporting.py, stograde/student/markdownify/markdownify.py, stograde/student/markdownify/supporting.py, stograde/toolkit/__main__.py
Allow the architecture to be specified for an assignment using `architecture: armv7l`, for example
Allow the output name for a supporting file to be specified, i.e. using `[ 'input', 'output' ]`.
(Specifying a single name or not putting it in an array will have the same behavior as before.)
=> Additions to spec options

README.md, stograde/specs/cache.py, stograde/toolkit/__main__.py, stograde/webapp/web_cli.py
- Check if 'files' is in the spec before processing
- Check that 'files' and 'tests' are not empty before processing
- Fix #107 
- Update web CLI to use new supporting file functions
=> Catch error when 'files' not in spec

stograde/specs/util.py
Fix an issue with the arch check where the system's arch string would have a newline which would fail the check, even on the correct architecture.
=> Remove trailing whitespace/newlines from arch to fix check

stograde/specs/cache.py, stograde/toolkit/__main__.py, stograde/toolkit/args.py
Allow yaml files to be specified in a new format that improves readability.
Instead of using a single array to hold all information for a file or test, split parts into `file`, `commands`, `options`, like they are in the cached json.
This new format is activated by adding `spec_version: 3` to the spec.
This may make specs longer, but makes them easier to understand for those new to creating specs.
Example usage:
```yaml
---
assignment: hw1
compilers:
- &cpp 'g++ --std=c++11 $@ -o $@.exec'
- &server 'g++ --std=c++11 $@ $SERVER'
files:
- [ hello.cpp, *server, web: true ]
- [ hw1_questions.txt ]
- [ Makefile ]
- [ Dog.h ]
- [ Dog.cpp ]
- - tryDog.cpp
- rm -f tryDog tryDog.o Dog.o
- make
tests:
- [ tryDog.cpp, ./tryDog ]
inputs:
- prelude
- postlude
- sd_fun.h
```
becomes
```yaml
--- …
```
=> Improve readability of yaml files

stograde/student/markdownify/process_file.py
If a webfile is being compiled, make sure that the server directory exists before compiling.
Currently the main method only creates it if the --web or --ci, causing compilation issues for web files when only being recorded if the directory had not been created earlier.
=> Ensure server directory exists whenever web file is compiled

setup.py, stograde/toolkit/__main__.py, stograde/toolkit/args.py, stograde/toolkit/download_specs.py, stograde/toolkit/stogit_url.py, test/toolkit/test_args.py
When the data directory already has specs but a new student is added, the StoGit URL for them is messed up unless if --course is specified.
Students already with their repository cloned into students are fine because their directory exists and it updates based on that.
- Moves the StoGit URL calculation until later
- Calculates URL based on the spec repository if necessary
- Alerts user that the toolkit is inferring the course from the specs
=> Fix StoGit URL bug

stograde/toolkit/ci_analyze.py
Because labs are done during multiple homeworks, the failing builds can be annoying. This prevents labs from failing CI builds.
=> Don't fail CI build if labs are incomplete

stograde/formatters/markdown.py
Adds markdown code blocks with the file's extension to allow editors like VS Code to highlight the code appropriately.
E.g.:
```
int main() {
return 0;
}
```
becomes:
```cpp
int main() {
return 0;
}
```
=> Markdown code highlighting

README.md, stograde/specs/__init__.py, stograde/specs/cache.py, stograde/student/markdownify/markdownify.py, stograde/student/markdownify/process_file.py, stograde/student/markdownify/supporting.py, stograde/toolkit/__main__.py, stograde/webapp/web_cli.py, test/integration_tests/fixtures/two_students_hw1/data/specs/hw1.yaml
- Increase readability of specs by moving tests to the file under `files:` they are associated with
- Both listing tests with the file and under a separate `tests` section can be done in the same spec, even for the same file
- `supporting` tag added
- Same functionality as `inputs`, added to make specs clearer
- Both `supporting` and `inputs` can be used in the same spec
- Supporting files can be specified with a dict, in addition to a string or list as before:
```yaml
supporting:
- file1.txt                   # copy file to homework directory
- [ file2.txt, file2a.txt ]   # copy file to homework directory with rename/relocation
- file: file3.txt             # same as above but more verbose
destination: file3a.txt
```
- Spec versions can now be combined, no need to differentiate with …
=> Spec Improvements

setup.cfg, setup.py, stograde/toolkit/__main__.py, stograde/toolkit/args.py, stograde/toolkit/progress_bar.py, test/common/test_parse_commit_msg_for_assignments.py, test/formatters/test_tabulate.py, test/specs/test_spec.py, test/toolkit/test_config.py, test/toolkit/test_progress_bar.py, tox.ini
- Add dependencies for `stograde drive`.  This prevents errors where version would be too old and then would throw an error when the program is running
- Switch from `pytest-pep8` to `pytest-flake8` for pep8 testing. `pytest-pep8` does not seem to be actively maintained and now causes errors with newer versions of `pytest`
=> Add stograde drive dependencies

docs/GETTING_STARTED.md, docs/SPECS.md, stograde/formatters/html.py, stograde/formatters/markdown.py, stograde/process_assignment/process_assignment.py, stograde/process_file/file_result.py, stograde/process_file/process_file.py, stograde/specs/file_options.py, stograde/specs/spec.py, stograde/specs/spec_file.py, stograde/specs/supporting_file.py, test/formatters/results_for_tests.py, test/formatters/test_html.py, test/formatters/test_markdown.py, test/process_assignment/test_process_assignment.py, test/process_file/fixtures/another_file.txt, test/process_file/test_process_file.py, test/specs/test_spec_file.py, test/student/test_record_student.py
Allow files to have alternative names in case the student misnames their file
- If the file cannot be found, any alternate names will be searched for
- If alternate names are specified and a file is found, other alternate names will be searched for and, if found, will be listed to alert the TA that multiple files could be the one the student intended to turn in
=> Alternate names
