StoDevX/stograde

README.md
=> Add fish instructions to the README

cs251tk/toolkit/args.py
=> Switch to sd-s17 as the base url default

cs251tk/cli/cs251tk.py
=> Don't tabulate when --quiet is set

.gitignore, .travis.yml, cs251tk/toolkit/save_recordings.py, cs251tk/toolkit/test_tabulate.py, setup.py, tox.ini
Currently, we only have one unit test, but that can and will change.
=> Add TravisCI for automated testing

bin/fix-sound-lab.py, bin/hw7.py, cs251tk/common/run.py, cs251tk/formatters/markdown.py, cs251tk/student/markdownify.py, cs251tk/toolkit/tabulate.py, setup.cfg, tox.ini
https://www.python.org/dev/peps/pep-0008/
A python styleguide. Think gofmt, or prettier, or rustfmt. But for python.
=> Add PEP8 linting

.gitignore, .travis.yml, cs251tk/common/test_flatten.py, setup.cfg, tox.ini
And integration with Coveralls.io: https://coveralls.io/github/StoDevX/cs251-toolkit
=> Add code coverage checks

cs251tk/toolkit/args.py, cs251tk/toolkit/test_args.py
=> Add cs251tk argument tests

cs251tk/toolkit/test_get_students.py, tox.ini
and hey, I found a really, really nice filesystem mocking library! woot!
=> Add tests for get_students function

cs251tk/common/run.py
=> capture and return stdout from run()

cs251tk/common/test_run.py
Success, input_data, timeout, and not found commands.
=> Add tests for run()

cs251tk/student/markdownify/pipe.py, cs251tk/student/markdownify/test_cat.py, cs251tk/student/markdownify/test_pipe.py, cs251tk/student/markdownify/test_truncate.py
=> More tests

.travis.yml, script/pick-docker-tag, script/run-docker
Since this is a fairly trivial process, I figure it makes sense to loop it into our CI chain.  It'll also make installing everything *much* easier.
=> Build Our Docker Image in Travis

README.md, cs251tk/toolkit/args.py
- Remove venv instructions from the README
- Update the help page and arguments details in the README
- Update maintenance instructions in the README
=> README cleanups

cs251tk/toolkit/tabulate.py, cs251tk/toolkit/test_tabulate.py
They've always been a bit of a pain, and they don't bring very much to the output.
If you feel otherwise, let me know and I'll bring them back.
=> Remove the fancy table encodings

integration_tests/test_e2e.py
1. testing `--quiet`
2. testing `--record=hw1`
=> More end-to-end tests

script/deploy
This resolves [some build errors](https://travis-ci.org/StoDevX/cs251-toolkit/jobs/206837511#L503-L1163), hopefully.
I'm just going to merge this once CI is green since it's deploy-only and nobody really needs to worry about it.
=> Simplify script/deploy

cs251tk/referee/__init__.py, cs251tk/referee/__main__.py, cs251tk/toolkit/__init__.py, cs251tk/toolkit/__main__.py, integration_tests/test_e2e.py, setup.py
Let's see if a) I broke any tests and b) if the tests catch anything. This works locally.
=> Move CLI entry points to <module>/__main__.py

cs251tk/formatters/__init__.py, cs251tk/formatters/html.py, cs251tk/referee/emailify.py, cs251tk/referee/process_student.py, cs251tk/referee/send_email.py, cs251tk/toolkit/__main__.py
This does some initial fixups for referee.
It also creates an HTML formatter for use in sending multipart/mime emails.
With this, referee pretty much needs a vm to run on with docker + a server, and a cgi-bin script that can call the commands.
=> Referee hacks stuffs

.travis.yml, script/docker-build, script/docker-deploy, script/github-latest-release, script/lib/script.rb, script/lib/script/runner.rb
Now we build once and re-tag for everything we want to push to! This is faster, lighter, cooler, and generally smarter.
=> Update Travis Pipeline to Deploy Stuff Smarter

setup.py
After bumping, we just need to make a tag. We can do that via Github, by creating a "release".
- Finished initial implementation of the `referee` "server"
=> Bump version to v2.2.0

.travis.yml, cs251tk/common/test_run.py
=> Python 3.7

README.md, cs251tk/student/analyze.py, cs251tk/student/markdownify/markdownify.py, cs251tk/toolkit/__main__.py, cs251tk/toolkit/args.py, cs251tk/toolkit/process_student.py, cs251tk/toolkit/tabulate.py, cs251tk/toolkit/test_tabulate.py, integration_tests/fixtures/two_students_hw1/data/specs/ws1.yaml, integration_tests/test_e2e.py, setup.py
Increment version to 2.2.1 and tag pre-release with 2.2.1-beta
Added a new type of assignment: ws (worksheet)
Added integration with a new program: CheckDates
CheckDates finds the first submission for the assignment and adds it to the log file.
CheckDates is not required for cs251tk to run. Currently CheckDates is only in the [Hardware Design Specs](https://github.com/maxnz/cs241-specs) repository.
Works on the Windows Linux Subsystem - needs to be tested on macOS and Linux.
=> Add support for Hardware Design Worksheets and Integration with CheckDates program

.travis.yml
=> move pypi deploy job to post-docker

README.md
pip3 apparently does not have a --update flag
=> Changed --update to --upgrade

cs251tk/specs/load.py, cs251tk/toolkit/__main__.py, cs251tk/toolkit/args.py, cs251tk/toolkit/config.py
Adds capability to check for spec updates with git fetch and a git log comparison. If an update is found, the user is asked if they want to pull the update from the remote repository.
If the data directory is not found, the user is asked if they want to download specs. If yes, it asks which class.
Fixes #79 and closes #10
=> Add spec update

cs251tk/formatters/markdown.py, cs251tk/specs/load.py, cs251tk/student/markdownify/check_submit_date.py, cs251tk/student/markdownify/markdownify.py, cs251tk/student/record.py, cs251tk/toolkit/__main__.py, setup.py
Ports the C++ program CheckDates to Python and includes it in the toolkit. Closes #89.
#87 should be merged first.
=> Port checkdates

.travis.yml
=> travis: Use xenial as dist

cs251tk/toolkit/__main__.py, cs251tk/toolkit/args.py
=> Catch invalid spec ids

cs251tk/student/markdownify/markdownify.py, cs251tk/student/markdownify/process_file.py
They can differ between assignments and thus should each have their own copy
=> Move where the toolkit looks for the software design webapp files

cs251tk/student/markdownify/markdownify.py, cs251tk/student/markdownify/process_file.py, cs251tk/student/record.py, cs251tk/toolkit/__main__.py, cs251tk/toolkit/args.py, cs251tk/toolkit/process_student.py
While testing the new ci with a couple of SD students, I've run into errors such as the following:
I've added an option that will bypass this issue until it can be fixed.
=> Skip ci web compile

.travis.yml
I'm keeping Py3.4 around for the lab computers
=> update Travis to Py3.7

cs251tk/toolkit/__main__.py, cs251tk/toolkit/args.py, cs251tk/webapp/server.py, cs251tk/webapp/web_cli.py
- Fix issue where files wouldn't compile properly when using the CLI
- Adds the option to specify the port the server will be hosted at
- Missing optional files won't fail the CI build
- Catch KeyErrors caused by the CI check
=> CLI Improvements and Bugfix

stograde/student/remove.py, stograde/toolkit/__main__.py, stograde/toolkit/args.py, stograde/toolkit/ci_analyze.py, stograde/webapp/web_cli.py
Fix issue where running clean without having the student's directory present would cause an exception
Fix issue where specifying course as hd-f19 would create a stogit url of git@stogit.cs.stolaf.edu:hd-f19-f19
Extracting of a couple of parts of main into separate functions
Couple of small improvements to web cli, such as checking if a spec contains any web files before the cli is loaded
=> Improve ci and web

.travis.yml
Found one thing to update so far
=> Fix Travis-ci

.travis.yml, Dockerfile, README.md, script/crontab, script/deploy, script/github-latest-release, script/referee-cgi-bin.sh, script/run-docker, stograde/referee/send_email.py, stograde/specs/cache.py, test/integration_tests/test_e2e.py
yep.
I think this is everything.
=> Continue stoGrade rename

bin/fix-sound-lab.py, bin/generate-email.py, stograde/toolkit/__main__.py, stograde/toolkit/config.py
=> add `encoding='utf-8'` to remaining open() calls

.travis.yml, Dockerfile.gcc, stograde/toolkit/ci_analyze.py
=> Add Dockerfile.gcc and deploy script for version-gcc

.travis.yml
This might fix the travis build failure for the -gcc docker image
=> Try removing parenthesis from .travis.yml

stograde/toolkit/__main__.py, stograde/toolkit/args.py, test/toolkit/test_args.py
Reflect change in naming of class groups (using sd/s20 instead of sd-s20)
=> Update StoGit URLs

stograde/student/markdownify/process_file.py, stograde/toolkit/__main__.py, stograde/webapp/server.py
Incorporate new version of the server into toolkit
After this, we should be ready for a 3.0.0
=> Update server with new version

stograde/toolkit/__main__.py
Was looking for cache directory in wrong place when re-cache flag triggered the re-caching
=> Fix forced re-caching

.travis.yml
also trying to poke coveralls…
=> Add python3.8 to travis test matrix

stograde/common/check_submit_date.py, stograde/process_file/process_file.py
Fix a couple places where the use of `RunStatus` instead of `str` had not been updated
=> RunStatus bugfixes

.travis.yml, script/docker-deploy, setup.py, tox.ini
Also fix issue with setuptools in tox venv being too old
=> Add a check for whether there actually are any targets to deploy

script/docker-deploy
Add an apt-get update at the beginning of the install steps for docker buildx
=> Improve docker-deploy
